set(FILES
    Include/GlobePopulation/GlobePopulationBus.h
    Include/GlobePopulation/GlobePopulationTypeIds.h
    Source/GlobePopulationModuleInterface.h
    Source/GlobePopulationModuleInterface.cpp
    Source/Clients/GlobePopulationSystemComponent.h
    Source/Clients/GlobePopulationSystemComponent.cpp
    Source/Clients/PopulationMarkerComponent.h
    Source/Clients/PopulationMarkerComponent.cpp
    Source/Utils/IonApiClient.h
    Source/Utils/IonApiClient.cpp
    Source/Utils/TokenLoader.h
)
